# Generated by Django 3.0.7 on 2020-09-01 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='bdzfb',
        ),
    ]
